/**
 * Generated by Universal SVG Studio
 * Character: おねちゃん (ONE)
 */
import { AnimationTimeline, AvatarDef, PartState, AvatarPartDef, getTransformStr, getStrokeStr } from './SvgAnimation/OneSvgAnimator';

export const animationTimeline: AnimationTimeline = {
  "duration": 2000,
  "loop": true,
  "bgColor": "#feaa34",
  "transparentBg": true,
  "keyframes": [
    {
      "time": 0,
      "parts": {
        "all": {
          "x": 0,
          "y": 0,
          "scaleX": 1.06,
          "scaleY": 0.94,
          "rotate": -9,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "backHairBase": {
          "x": 0,
          "y": 0,
          "scaleX": 1.1,
          "scaleY": 1,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": true,
          "visible": true,
          "shape": "normal"
        },
        "leftWing": {
          "x": 0,
          "y": 0,
          "scaleX": 1,
          "scaleY": 1.5,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "rightWing": {
          "x": 0,
          "y": 0,
          "scaleX": 1,
          "scaleY": 1.5,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "face": {
          "x": 0,
          "y": 0,
          "scaleX": 1.1,
          "scaleY": 1.2,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "frontHair": {
          "x": 0,
          "y": 0,
          "scaleX": 1.2,
          "scaleY": 1.3,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "leftEye": {
          "x": 0,
          "y": 0,
          "scaleX": 0.53,
          "scaleY": 1.38,
          "rotate": 0,
          "strokeWidth": 7,
          "strokeColor": "#0EA5E9",
          "useCustomStroke": true,
          "visible": true,
          "shape": "normal"
        },
        "rightEye": {
          "x": 0,
          "y": 0,
          "scaleX": 0.53,
          "scaleY": 1.38,
          "rotate": 0,
          "strokeWidth": 7,
          "strokeColor": "#0EA5E9",
          "useCustomStroke": true,
          "visible": true,
          "shape": "normal"
        },
        "mouth": {
          "x": 0,
          "y": 5.7,
          "scaleX": 1,
          "scaleY": 1,
          "rotate": 0,
          "strokeWidth": 1,
          "strokeColor": "#292524",
          "useCustomStroke": true,
          "visible": true,
          "shape": "smile"
        }
      }
    },
    {
      "time": 49.52,
      "parts": {
        "all": {
          "x": 0,
          "y": 0,
          "scaleX": 1.06,
          "scaleY": 0.94,
          "rotate": 8,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "backHairBase": {
          "x": 0,
          "y": 0,
          "scaleX": 1.1,
          "scaleY": 1,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": true,
          "visible": true,
          "shape": "normal"
        },
        "leftWing": {
          "x": 0,
          "y": 0,
          "scaleX": 1,
          "scaleY": 1.5,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "rightWing": {
          "x": 0,
          "y": 0,
          "scaleX": 1,
          "scaleY": 1.5,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "face": {
          "x": 0,
          "y": 0,
          "scaleX": 1.1,
          "scaleY": 1.2,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "frontHair": {
          "x": 0,
          "y": 0,
          "scaleX": 1.2,
          "scaleY": 1.3,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "leftEye": {
          "x": 0,
          "y": 0,
          "scaleX": 0.53,
          "scaleY": 1.38,
          "rotate": 0,
          "strokeWidth": 7,
          "strokeColor": "#0EA5E9",
          "useCustomStroke": true,
          "visible": true,
          "shape": "normal"
        },
        "rightEye": {
          "x": 0,
          "y": 0,
          "scaleX": 0.53,
          "scaleY": 1.38,
          "rotate": 0,
          "strokeWidth": 7,
          "strokeColor": "#0EA5E9",
          "useCustomStroke": true,
          "visible": true,
          "shape": "normal"
        },
        "mouth": {
          "x": 0,
          "y": 5.7,
          "scaleX": 1,
          "scaleY": 1,
          "rotate": 0,
          "strokeWidth": 1,
          "strokeColor": "#292524",
          "useCustomStroke": true,
          "visible": true,
          "shape": "smile"
        }
      }
    },
    {
      "time": 99.62,
      "parts": {
        "all": {
          "x": 0,
          "y": 0,
          "scaleX": 1.06,
          "scaleY": 0.94,
          "rotate": -9,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "backHairBase": {
          "x": 0,
          "y": 0,
          "scaleX": 1.1,
          "scaleY": 1,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": true,
          "visible": true,
          "shape": "normal"
        },
        "leftWing": {
          "x": 0,
          "y": 0,
          "scaleX": 1,
          "scaleY": 1.5,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "rightWing": {
          "x": 0,
          "y": 0,
          "scaleX": 1,
          "scaleY": 1.5,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "face": {
          "x": 0,
          "y": 0,
          "scaleX": 1.1,
          "scaleY": 1.2,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "frontHair": {
          "x": 0,
          "y": 0,
          "scaleX": 1.2,
          "scaleY": 1.3,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "leftEye": {
          "x": 0,
          "y": 0,
          "scaleX": 0.53,
          "scaleY": 1.38,
          "rotate": 0,
          "strokeWidth": 7,
          "strokeColor": "#0EA5E9",
          "useCustomStroke": true,
          "visible": true,
          "shape": "normal"
        },
        "rightEye": {
          "x": 0,
          "y": 0,
          "scaleX": 0.53,
          "scaleY": 1.38,
          "rotate": 0,
          "strokeWidth": 7,
          "strokeColor": "#0EA5E9",
          "useCustomStroke": true,
          "visible": true,
          "shape": "normal"
        },
        "mouth": {
          "x": 0,
          "y": 5.7,
          "scaleX": 1,
          "scaleY": 1,
          "rotate": 0,
          "strokeWidth": 1,
          "strokeColor": "#292524",
          "useCustomStroke": true,
          "visible": true,
          "shape": "smile"
        }
      }
    }
  ]
};


// =====================================================================
// レンダリングロジックのヘルパー関数
// =====================================================================
const renderEyeLogic = (s: PartState, g: PartState, d: AvatarPartDef, side: 'left' | 'right'): string => {
  const width = s.useCustomStroke ? s.strokeWidth : g.strokeWidth;
  const color = s.useCustomStroke ? s.strokeColor : g.strokeColor;
  const baseColor = width > 0 ? '#FFFFFF' : '#0EA5E9';
  const lineColor = width > 0 ? color : '#0EA5E9';
  const cx = d.cx;
  const cy = d.cy;
  
  let node = '';
  if (s.shape === 'normal') node = `<circle cx="${cx}" cy="${cy}" r="3.5" fill="${baseColor}" ${getStrokeStr(s, g)} />`;
  else if (s.shape === 'happy') node = `<path d="M ${cx-4} ${cy+1} Q ${cx} ${cy-3} ${cx+4} ${cy+1}" fill="none" stroke="${lineColor}" stroke-width="${width>0?width:2.5}" stroke-linecap="round" />`;
  else if (s.shape === 'closed') node = `<path d="M ${cx-4} ${cy} L ${cx+4} ${cy}" fill="none" stroke="${lineColor}" stroke-width="${width>0?width:2.5}" stroke-linecap="round" />`;
  else if (s.shape === 'sad') node = `<path d="M ${cx-4} ${cy-1} Q ${cx} ${cy+3} ${cx+4} ${cy-1}" fill="none" stroke="${lineColor}" stroke-width="${width>0?width:2.5}" stroke-linecap="round" />`;
  else if (s.shape === 'angry') { const pathD = side === 'left' ? `M ${cx-4} ${cy-2} L ${cx+4} ${cy+1}` : `M ${cx-4} ${cy+1} L ${cx+4} ${cy-2}`; node = `<path d="${pathD}" fill="none" stroke="${lineColor}" stroke-width="${width>0?width:2.5}" stroke-linecap="round" />`; }
  else if (s.shape === 'half') node = `<path d="M ${cx-4.5} ${cy} L ${cx+4.5} ${cy} A 4.5 4.5 0 0 1 ${cx-4.5} ${cy} Z" fill="${baseColor}" ${getStrokeStr(s, g)} />`;
  else if (s.shape === 'star') { const pts = Array.from({length: 10}).map((_, i) => { const r = i % 2 === 0 ? 4.5 : 1.8; return `${cx + r * Math.cos(-Math.PI/2 + i * Math.PI/5)},${cy + r * Math.sin(-Math.PI/2 + i * Math.PI/5)}`; }).join(' '); node = `<polygon points="${pts}" fill="${baseColor}" ${getStrokeStr(s, g)} />`; }
  else if (s.shape === 'heart') { const heartD = `M ${cx} ${cy+1.5} C ${cx} ${cy-1} ${cx-3.5} ${cy-4.5} ${cx-5.5} ${cy-2} C ${cx-7} ${cy+0.5} ${cx-3.5} ${cy+3.5} ${cx} ${cy+6} C ${cx+3.5} ${cy+3.5} ${cx+7} ${cy+0.5} ${cx+5.5} ${cy-2} C ${cx+3.5} ${cy-4.5} ${cx} ${cy-1} ${cx} ${cy+1.5} Z`; node = `<path d="${heartD}" fill="${baseColor}" transform="translate(0, -2)" ${getStrokeStr(s, g)} />`; }
  else if (s.shape === 'dizzy') {
     let dStr = `M ${cx} ${cy} `; let rVal = 0; let ang = 0;
     for(let i=0; i<=20; i++){ ang += Math.PI/3; rVal += 0.25; dStr += `L ${cx + Math.cos(ang)*rVal} ${cy + Math.sin(ang)*rVal} `; }
     node = `<path d="${dStr}" fill="none" stroke="${lineColor}" stroke-width="${width>0?width:1.5}" stroke-linecap="round" stroke-linejoin="round" />`;
  }
  else if (s.shape === 'sparkle') node = `<path d="M ${cx} ${cy-4} L ${cx+1} ${cy-1} L ${cx+4} ${cy} L ${cx+1} ${cy+1} L ${cx} ${cy+4} L ${cx-1} ${cy+1} L ${cx-4} ${cy} L ${cx-1} ${cy-1} Z" fill="${baseColor}" ${getStrokeStr(s, g)} />`;
  else if (s.shape === 'cry') node = `<circle cx="${cx}" cy="${cy}" r="3.5" fill="${baseColor}" ${getStrokeStr(s, g)} /><circle cx="${cx-2}" cy="${cy+2}" r="1.5" fill="#38BDF8" />`;
  else if (s.shape === 'wide') node = `<circle cx="${cx}" cy="${cy}" r="4.5" fill="${baseColor}" ${getStrokeStr(s, g)} /><circle cx="${cx}" cy="${cy}" r="1.5" fill="${lineColor}" />`;
  else if (s.shape === 'dead') node = `<circle cx="${cx}" cy="${cy}" r="2.5" fill="${lineColor}" ${getStrokeStr(s, g)} />`;
  
  return `<g ${getTransformStr(s, cx, cy)}>${node}</g>`;
};

const renderMouthLogic = (s: PartState, g: PartState, d: AvatarPartDef): string => {
  const width = s.useCustomStroke ? s.strokeWidth : g.strokeWidth;
  const color = s.useCustomStroke ? s.strokeColor : g.strokeColor;
  const fillColor = width > 0 ? '#FFFFFF' : '#292524';
  const lineColor = width > 0 ? color : '#292524';
  const cx = d.cx;
  const cy = d.cy;

  let node = '';
  if (s.shape === 'normal') node = `<circle cx="${cx}" cy="${cy}" r="1.5" fill="${fillColor}" ${getStrokeStr(s, g)} />`;
  else if (s.shape === 'smile') node = `<path d="M ${cx-4} ${cy-1} Q ${cx} ${cy+3} ${cx+4} ${cy-1}" fill="none" stroke="${lineColor}" stroke-width="${width>0?width:2}" stroke-linecap="round" />`;
  else if (s.shape === 'open') node = `<path d="M ${cx-4} ${cy-1} Q ${cx} ${cy+5} ${cx+4} ${cy-1} Z" fill="${fillColor}" stroke="${lineColor}" stroke-width="${width>0?width:0}" stroke-linejoin="round" />`;
  else if (s.shape === 'cat') node = `<path d="M ${cx-4} ${cy-1} Q ${cx-2} ${cy+2} ${cx} ${cy} Q ${cx+2} ${cy+2} ${cx+4} ${cy-1}" fill="none" stroke="${lineColor}" stroke-width="${width>0?width:2}" stroke-linecap="round" stroke-linejoin="round" />`;
  else if (s.shape === 'sad') node = `<path d="M ${cx-4} ${cy+2} Q ${cx} ${cy-2} ${cx+4} ${cy+2}" fill="none" stroke="${lineColor}" stroke-width="${width>0?width:2}" stroke-linecap="round" />`;
  else if (s.shape === 'straight') node = `<path d="M ${cx-3} ${cy} L ${cx+3} ${cy}" fill="none" stroke="${lineColor}" stroke-width="${width>0?width:2}" stroke-linecap="round" />`;
  else if (s.shape === 'triangle') node = `<polygon points="${cx-3},${cy-1} ${cx+3},${cy-1} ${cx},${cy+3.5}" fill="${fillColor}" stroke="${lineColor}" stroke-width="${width>0?width:0}" stroke-linejoin="round" />`;
  else if (s.shape === 'shock') node = `<circle cx="${cx}" cy="${cy+1}" r="2.5" fill="${fillColor}" ${getStrokeStr(s, g)} />`;
  else if (s.shape === 'zigzag') node = `<path d="M ${cx-5} ${cy-1} L ${cx-2.5} ${cy+2} L ${cx} ${cy-1} L ${cx+2.5} ${cy+2} L ${cx+5} ${cy-1}" fill="none" stroke="${lineColor}" stroke-width="${width>0?width:2}" stroke-linecap="round" stroke-linejoin="round" />`;
  else if (s.shape === 'laugh') node = `<path d="M ${cx-4} ${cy-1} L ${cx+4} ${cy-1} A 4 4 0 0 1 ${cx-4} ${cy-1} Z" fill="${fillColor}" stroke="${lineColor}" stroke-width="${width>0?width:0}" stroke-linejoin="round" />`;
  else if (s.shape === 'wobbly') node = `<path d="M ${cx-5} ${cy} Q ${cx-3.75} ${cy-2} ${cx-2.5} ${cy} T ${cx} ${cy} T ${cx+2.5} ${cy} T ${cx+5} ${cy}" fill="none" stroke="${lineColor}" stroke-width="${width>0?width:2}" stroke-linecap="round" />`;
  else if (s.shape === 'pout') node = `<path d="M ${cx-3} ${cy+1} Q ${cx} ${cy-1} ${cx+3} ${cy+1}" fill="none" stroke="${lineColor}" stroke-width="${width>0?width:2}" stroke-linecap="round" />`;
  
  return `<g ${getTransformStr(s, cx, cy)}>${node}</g>`;
};

// =====================================================================
// アバター構造定義 (AvatarDef)
// =====================================================================
export const onechanAvatarDef: AvatarDef = {
  id: 'onechan',
  name: 'おねちゃん (ONE)',
  viewBox: '0 0 100 100',
  defs: `
    <linearGradient id="hairGrad" x1="0" y1="0" x2="0" y2="100" gradientUnits="userSpaceOnUse">
      <stop offset="25%" stop-color="#F8FAFC" />
      <stop offset="60%" stop-color="#FFEDD5" />
      <stop offset="95%" stop-color="#EA580C" />
    </linearGradient>
  `,
  parts: [
    {
      id: 'all', 
      name: '全体（Global）', 
      isGlobal: true, 
      cx: 50, cy: 50,
      render: () => '' 
    },
    {
      id: 'backHairBase', 
      name: '後ろ髪（ベース）', 
      cx: 50, cy: 50,
      render: (s: PartState, g: PartState, d: AvatarPartDef) => `<path d="M 20 25 Q 50 0 80 25 L 76 46 L 86 80 Q 50 90 14 80 L 24 46 Z" fill="url(#hairGrad)" ${getTransformStr(s, d.cx, d.cy)} ${getStrokeStr(s, g)} />`
    },
    {
      id: 'leftWing', 
      name: '左のハネ', 
      cx: 28, cy: 42,
      render: (s: PartState, g: PartState, d: AvatarPartDef) => `<path d="M 35 25 L 4 35 L 26 55 Z" fill="url(#hairGrad)" ${getTransformStr(s, d.cx, d.cy)} ${getStrokeStr(s, g)} />`
    },
    {
      id: 'rightWing', 
      name: '右のハネ', 
      cx: 72, cy: 42,
      render: (s: PartState, g: PartState, d: AvatarPartDef) => `<path d="M 65 25 L 96 35 L 74 55 Z" fill="url(#hairGrad)" ${getTransformStr(s, d.cx, d.cy)} ${getStrokeStr(s, g)} />`
    },
    {
      id: 'face', 
      name: '顔（輪郭）', 
      cx: 50, cy: 56,
      render: (s: PartState, g: PartState, d: AvatarPartDef) => `<circle cx="${d.cx}" cy="${d.cy}" r="23" fill="#FFFFFF" ${getTransformStr(s, d.cx, d.cy)} ${getStrokeStr(s, g)} />`
    },
    {
      id: 'frontHair', 
      name: '前髪・サイド', 
      cx: 50, cy: 45,
      render: (s: PartState, g: PartState, d: AvatarPartDef) => `<path d="M 27 30 Q 50 23 73 30 L 76 68 Q 66 58 63 46 L 56 46 L 50 43 L 44 46 L 37 46 Q 34 58 24 68 Z" fill="url(#hairGrad)" ${getTransformStr(s, d.cx, d.cy)} ${getStrokeStr(s, g)} />`
    },
    {
      id: 'leftEye', 
      name: '左目', 
      cx: 41, cy: 59,
      shapes: [ 
        {id: 'normal', label: '標準'}, {id: 'happy', label: '笑顔'}, {id: 'closed', label: '閉じ'}, 
        {id: 'sad', label: '悲しみ'}, {id: 'angry', label: '怒り'}, {id: 'half', label: 'ジト目'}, 
        {id: 'star', label: '星'}, {id: 'heart', label: 'ハート'}, {id: 'dizzy', label: 'ぐるぐる'},
        {id: 'sparkle', label: 'キラキラ'}, {id: 'cry', label: '涙目'}, {id: 'wide', label: '見開き'}, {id: 'dead', label: '虚無'}
      ],
      render: (s: PartState, g: PartState, d: AvatarPartDef) => renderEyeLogic(s, g, d, 'left')
    },
    {
      id: 'rightEye', 
      name: '右目', 
      cx: 59, cy: 59,
      shapes: [ 
        {id: 'normal', label: '標準'}, {id: 'happy', label: '笑顔'}, {id: 'closed', label: '閉じ'}, 
        {id: 'sad', label: '悲しみ'}, {id: 'angry', label: '怒り'}, {id: 'half', label: 'ジト目'}, 
        {id: 'star', label: '星'}, {id: 'heart', label: 'ハート'}, {id: 'dizzy', label: 'ぐるぐる'},
        {id: 'sparkle', label: 'キラキラ'}, {id: 'cry', label: '涙目'}, {id: 'wide', label: '見開き'}, {id: 'dead', label: '虚無'}
      ],
      render: (s: PartState, g: PartState, d: AvatarPartDef) => renderEyeLogic(s, g, d, 'right')
    },
    {
      id: 'mouth', 
      name: '口', 
      cx: 50, cy: 66,
      shapes: [ 
        {id: 'normal', label: '標準'}, {id: 'smile', label: '微笑み'}, {id: 'open', label: '開口'}, 
        {id: 'cat', label: '猫口'}, {id: 'sad', label: '悲しみ'}, {id: 'straight', label: '一文字'}, 
        {id: 'triangle', label: '牙'}, {id: 'shock', label: '驚き'}, {id: 'zigzag', label: 'ギザギザ'},
        {id: 'laugh', label: 'ニカッ'}, {id: 'wobbly', label: '波線'}, {id: 'pout', label: 'への字'} 
      ],
      render: (s: PartState, g: PartState, d: AvatarPartDef) => renderMouthLogic(s, g, d)
    }
  ]
};