/**
 * Generated by Universal SVG Studio
 * Character: おねちゃん (ONE)
 */
import { AnimationTimeline } from './SvgAnimation/OneSvgAnimator';

export const animationTimeline: AnimationTimeline = {
  "duration": 2000,
  "loop": true,
  "bgColor": "#feaa34",
  "transparentBg": true,
  "keyframes": [
    {
      "time": 0,
      "parts": {
        "all": {
          "x": 0,
          "y": 0,
          "scaleX": 1.06,
          "scaleY": 0.94,
          "rotate": -9,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "backHairBase": {
          "x": 0,
          "y": 0,
          "scaleX": 1.1,
          "scaleY": 1,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": true,
          "visible": true,
          "shape": "normal"
        },
        "leftWing": {
          "x": 0,
          "y": 0,
          "scaleX": 1,
          "scaleY": 1.5,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "rightWing": {
          "x": 0,
          "y": 0,
          "scaleX": 1,
          "scaleY": 1.5,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "face": {
          "x": 0,
          "y": 0,
          "scaleX": 1.1,
          "scaleY": 1.2,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "frontHair": {
          "x": 0,
          "y": 0,
          "scaleX": 1.2,
          "scaleY": 1.3,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "leftEye": {
          "x": 0,
          "y": 0,
          "scaleX": 0.53,
          "scaleY": 1.38,
          "rotate": 0,
          "strokeWidth": 7,
          "strokeColor": "#0EA5E9",
          "useCustomStroke": true,
          "visible": true,
          "shape": "normal"
        },
        "rightEye": {
          "x": 0,
          "y": 0,
          "scaleX": 0.53,
          "scaleY": 1.38,
          "rotate": 0,
          "strokeWidth": 7,
          "strokeColor": "#0EA5E9",
          "useCustomStroke": true,
          "visible": true,
          "shape": "normal"
        },
        "mouth": {
          "x": 0,
          "y": 5.7,
          "scaleX": 1,
          "scaleY": 1,
          "rotate": 0,
          "strokeWidth": 1,
          "strokeColor": "#292524",
          "useCustomStroke": true,
          "visible": true,
          "shape": "smile"
        }
      }
    },
    {
      "time": 49.52,
      "parts": {
        "all": {
          "x": 0,
          "y": 0,
          "scaleX": 1.06,
          "scaleY": 0.94,
          "rotate": 8,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "backHairBase": {
          "x": 0,
          "y": 0,
          "scaleX": 1.1,
          "scaleY": 1,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": true,
          "visible": true,
          "shape": "normal"
        },
        "leftWing": {
          "x": 0,
          "y": 0,
          "scaleX": 1,
          "scaleY": 1.5,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "rightWing": {
          "x": 0,
          "y": 0,
          "scaleX": 1,
          "scaleY": 1.5,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "face": {
          "x": 0,
          "y": 0,
          "scaleX": 1.1,
          "scaleY": 1.2,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "frontHair": {
          "x": 0,
          "y": 0,
          "scaleX": 1.2,
          "scaleY": 1.3,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "leftEye": {
          "x": 0,
          "y": 0,
          "scaleX": 0.53,
          "scaleY": 1.38,
          "rotate": 0,
          "strokeWidth": 7,
          "strokeColor": "#0EA5E9",
          "useCustomStroke": true,
          "visible": true,
          "shape": "normal"
        },
        "rightEye": {
          "x": 0,
          "y": 0,
          "scaleX": 0.53,
          "scaleY": 1.38,
          "rotate": 0,
          "strokeWidth": 7,
          "strokeColor": "#0EA5E9",
          "useCustomStroke": true,
          "visible": true,
          "shape": "normal"
        },
        "mouth": {
          "x": 0,
          "y": 5.7,
          "scaleX": 1,
          "scaleY": 1,
          "rotate": 0,
          "strokeWidth": 1,
          "strokeColor": "#292524",
          "useCustomStroke": true,
          "visible": true,
          "shape": "smile"
        }
      }
    },
    {
      "time": 99.62,
      "parts": {
        "all": {
          "x": 0,
          "y": 0,
          "scaleX": 1.06,
          "scaleY": 0.94,
          "rotate": -9,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "backHairBase": {
          "x": 0,
          "y": 0,
          "scaleX": 1.1,
          "scaleY": 1,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": true,
          "visible": true,
          "shape": "normal"
        },
        "leftWing": {
          "x": 0,
          "y": 0,
          "scaleX": 1,
          "scaleY": 1.5,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "rightWing": {
          "x": 0,
          "y": 0,
          "scaleX": 1,
          "scaleY": 1.5,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "face": {
          "x": 0,
          "y": 0,
          "scaleX": 1.1,
          "scaleY": 1.2,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "frontHair": {
          "x": 0,
          "y": 0,
          "scaleX": 1.2,
          "scaleY": 1.3,
          "rotate": 0,
          "strokeWidth": 0,
          "strokeColor": "#292524",
          "useCustomStroke": false,
          "visible": true,
          "shape": "normal"
        },
        "leftEye": {
          "x": 0,
          "y": 0,
          "scaleX": 0.53,
          "scaleY": 1.38,
          "rotate": 0,
          "strokeWidth": 7,
          "strokeColor": "#0EA5E9",
          "useCustomStroke": true,
          "visible": true,
          "shape": "normal"
        },
        "rightEye": {
          "x": 0,
          "y": 0,
          "scaleX": 0.53,
          "scaleY": 1.38,
          "rotate": 0,
          "strokeWidth": 7,
          "strokeColor": "#0EA5E9",
          "useCustomStroke": true,
          "visible": true,
          "shape": "normal"
        },
        "mouth": {
          "x": 0,
          "y": 5.7,
          "scaleX": 1,
          "scaleY": 1,
          "rotate": 0,
          "strokeWidth": 1,
          "strokeColor": "#292524",
          "useCustomStroke": true,
          "visible": true,
          "shape": "smile"
        }
      }
    }
  ]
};
